#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/4527e922-6bcc-43c5-8a9e-d6280d875b0b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight grnled;
  CloudLight redled;
  int waterLevel;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int trigPin1 = A1;
const int echoPin1 = A2;
#define rled A3
#define gled A5
unsigned long startMillis;
unsigned long currentMillis;
const unsigned long period = 10000;
long duration1;
int distance1;

void setup() {
  // Initialize serial and wait for port to open:
  pinMode(trigPin1, OUTPUT);
  pinMode(echoPin1, INPUT);
  pinMode(rled, OUTPUT);
  pinMode(gled, OUTPUT);
  digitalWrite(rled, LOW);
  digitalWrite(gled, LOW);
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  Serial.println(WiFi.localIP());
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  onWaterLevelChange();
  if (waterLevel <= 10)
  {
    onRedledChange();
  }
  else if (waterLevel > 10)
  {
    onGrnledChange();
  }
  idk();
}


/*
  Since WaterLevel is READ_WRITE variable, onWaterLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWaterLevelChange()  {
  // Add your code here to act upon WaterLevel change
  digitalWrite(trigPin1, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin1, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin1, LOW);
  duration1 = pulseIn(echoPin1, HIGH);
  waterLevel = duration1 * 0.034 / 2;
  Serial.print("Water Level: "); Serial.print(waterLevel); Serial.println(" cm");
}

void idk(){
  currentMillis = millis();
  if (currentMillis - startMillis >= period)
  {
    startMillis = currentMillis;
  }
}

/*
  Since Redled is READ_WRITE variable, onRedledChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRedledChange()  {
  // Add your code here to act upon Redled change
  redled= 1;
  grnled= 0;
  digitalWrite(gled, LOW);
  digitalWrite(rled, HIGH);
  Serial.println("Oh F*ck this Sh*t I'm Out");
}

/*
  Since Grnled is READ_WRITE variable, onGrnledChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGrnledChange()  {
  // Add your code here to act upon Grnled change
  grnled= 1;
  redled= 0;
  digitalWrite(gled, HIGH);
  digitalWrite(rled, LOW);
}

